config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do

  mount Sidekiq::Web => '/sidekiq'
  root 'home#index'

  resources :users, only: [:create, :show, :update, :edit]
  get 'register' => 'users#new'
  put 'change_password' => 'users#change_password'
  get 'verify' => 'user_verifications#update'

  resources :user_sessions, only: [:create, :destroy]
  get 'login' => 'user_sessions#new'

  resources :password_resets, only: [ :new, :create, :edit, :update ]
  resources :admins

  resources :institutions
  resources :buildings
  resources :orders

end

app/models/user_session.rb
class UserSession < Authlogic::Session::Base
  find_by_login_method :find_by_username_or_email

  validate :check_if_verified

  private

  def check_if_verified
    if attempted_record
      errors.add(:base, 'You have not yet verified your account') unless attempted_record.verified
    end
  end
end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController
  before_filter :require_user, only: :destroy

  def new
    @user_session = UserSession.new
  end

  def create
    @user_session = UserSession.new(user_session_params)
    if @user_session.save
      flash[:notice] = 'Login successful, welcome!'
      redirect_to root_path
    else
      render :new
    end
  end

  def destroy
    current_user_session.destroy
    flash[:notice] = 'Logout successful!'
    redirect_to root_path
  end

  private

  def user_session_params
    params.require(:user_session).permit(:username, :password, :remember_me)
  end
end

app/helpers/user_sessions_helper.rb
module UserSessionsHelper
end

app/views/user_sessions/new.html.erb
<div class="col-sm-4 center-block">
  <%= form_for @user_session, url: user_sessions_path, method: :post do |f| %>
      <% if @user_session.errors.any? %>
          <div class="alert alert-danger text-center" id="flash">
            <b><%= pluralize(@user_session.errors.count, 'error') %> prohibited this user from being saved:</b>
            <ul class="center">
              <% @user_session.errors.full_messages.each do |msg| %>
                  <li><%= msg %></li>
              <% end %>
            </ul>
          </div>
      <% end %>
      <h4>Login</h4>
      <div class="form-group">
        <%= f.text_field :username, class: 'form-control', placeholder: 'Username or email' %>
      </div>
      <div class="form-group">
        <%= f.password_field :password, class: 'form-control', placeholder: 'Password' %>
      </div>
      <div class="actions">
        <%= f.submit 'Login', class: 'btn btn-primary btn-sm pull-right' %>
        <%= link_to 'Register account', register_path, class: 'btn btn-link pull-right' %>
        <%= link_to 'Forgot your password?', new_password_reset_url, class: 'btn btn-link pull-right'%>
        <%= f.check_box :remember_me, class: 'checkbox-inline pull-left', style: 'margin-top:11px;' %>
        <%= f.label :remember_me, class: 'label label-primary pull-left', style: 'margin-left:5px; margin-top:9px;' %>
      </div>
  <% end %>
</div>