config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do

  mount Sidekiq::Web => '/sidekiq'
  root 'home#index'

  resources :users, only: [:create, :show, :update, :edit]
  get 'register' => 'users#new'
  put 'change_password' => 'users#change_password'
  get 'verify' => 'user_verifications#update'

  resources :user_sessions, only: [:create, :destroy]
  get 'login' => 'user_sessions#new'

  resources :password_resets, only: [ :new, :create, :edit, :update ]
  resources :admins

  resources :institutions
  resources :buildings
  resources :orders

end

app/views/layouts/_top_navigation_bar.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="<%= root_path %>">
        <b>Order app</b> - Dječji vrtić Koraci i Prvi Koraci
      </a>
    </div>
    <ul class="nav navbar-nav navbar-right">
      <% if current_user_session %>
        <%= render 'layouts/user_dropdown' %>
      <% end %>
    </ul>
  </div>
</nav>

app/views/layouts/_user_dropdown.html.erb
<% display_name = current_user.full_name %>
<% display_name = current_user.username if current_user.full_name == '' %>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
    <i class="fa fa-user"> <%= display_name  %> </i><span class="caret"></span>
  </a>
  <ul class="dropdown-menu">
    <li>
      <%=link_to ' My data ', user_path(current_user), class: 'fa fa-paperclip' %>
    </li>
    <% if current_user.role? :admin %>
        <li>
          <%=link_to ' Admin panel ', admins_path, class: 'fa fa-exclamation-triangle' %>
        </li>
    <% end %>
    <li role="separator" class="divider"></li>
    <li>
      <%=link_to ' Log out ', user_session_path(current_user_session), 'data-method' => :delete, class: 'fa fa-sign-out' %>
    </li>
  </ul>
</li>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Order app</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render 'layouts/top_navigation_bar' %>
<div class="row">
  <div class="col-sm-4 text-center center-block">
    <% flash.each do |type, message| %>
        <div class="alert <%= bootstrap_class_for(type) %>" id="flash">
          <%= message %>
        </div>
    <% end %>
  </div>
</div>
<div class="row">
  <%= yield %>
</div>
</body>
</html>